name: sensor_dsp_test
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=19.3.*
  - backcall=0.1.*
  - bleach=3.1.*
  - ca-certificates=2019.11.*
  - certifi=2019.11.*
  - decorator=4.4.*
  - importlib_metadata=1.3.*
  - ipykernel=5.1.*
  - ipython_genutils=0.2.*
  - jinja2=2.10.*
  - jsonschema=3.2.*
  - jupyter_client=5.3.*
  - jupyter_contrib_core=0.3.*
  - jupyter_core=4.6.*
  - jupyter_nbextensions_configurator=0.4.*
  - libcxx=4.0.*
  - libcxxabi=4.0.*
  - libedit=3.1.*
  - libffi=3.2.*
  - libsodium=1.0.*
  - markupsafe=1.1.*
  - mistune=0.8.*
  - more-itertools=8.0.*
  - nbconvert=5.6.*
  - nbformat=4.4.*
  - ncurses=6.*
  - notebook=6.0.*
  - openssl=1.1.*
  - pandoc=2.2.3.*
  - pandocfilters=1.4.*
  - parso=0.5.*
  - pexpect=4.7.*
  - pip=19.3.*
  - prometheus_client=0.7.*
  - prompt_toolkit=3.0.*
  - pygments=2.5.*
  - pyrsistent=0.15.*
  - python=3.7.*
  - python-dateutil=2.8.*
  - readline=7.*
  - setuptools=42.0.*
  - six=1.13.*
  - sqlite=3.30.*
  - testpath=0.4.*
  - tk=8.6.*
  - tornado=6.0.*
  - traitlets=4.3.*
  - wheel=0.33.*
  - xz=5.2.*
  - yaml=0.2.*
  - zeromq=4.3.*
  - zipp=0.6.*
  - zlib=1.2.*
  - pip:
    - appnope==0.1.*
    - bokeh==1.4.*
    - defusedxml==0.6.*
    - entrypoints==0.3
    - ipython==7.11.*
    - ipython-genutils==0.2.*
    - jedi==0.15.*
    - jupyter-contrib-core==0.3.*
    - jupyter-nbextensions-configurator==0.4.*
    - lxml==4.4.*
    - numpy==1.18.*
    - packaging==20.*
    - pandas==0.25.*
    - pickleshare==0.7.*
    - pillow==7.0.*
    - ptyprocess==0.6.*
    - pylab==0.0.*
    - pyparsing==2.4.*
    - pytz==2019.*
    - pyusb==1.0.*
    - pyvisa==1.10.*
    - pyvisa-py==0.3.*
    - pyyaml==5.*
    - pyzmq==18.1.*
    - send2trash==1.5.*
    - terminado==0.8.*
    - wcwidth==0.1.*
    - webencodings==0.5.*